# build
markdown: kramdown
remote-theme: Documentation

title: SciComp Docs
baseurl: /scicomp-docs

collections:
  about:
    output: true
  access:
    output: true
  hpc:
    output: true
  linux:
    output: true
  software:
    output: true
  help:
    output: true

# Tipue search settings
tipue_search:
  include:  
    pages: true
    collections: [about, access, hpc, linux, software, help]
